version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5439:5432
  rust-app:
    build:
      context: ../../
      dockerfile: scaffold/docker/Dockerfile
    command: sh -c "cargo watch -x run"
    environment:
      - RUST_LOG=debug
    ports:
      - 8123:80
    volumes:
      - ../../.:/rust-app