[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-app"
path = "src/app/services/rust-app/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6", features = ["runtime-actix-native-tls", "postgres"] }
actix-web = "4.3.1"
awc = "3.1.1"
log = "0.4.14"
env_logger = "0.10.0"
signal-hook = "0.3.15"
